// mediInstructions in prescription table == Schedule
// Add dosage to the screen, remove image and description.
// Get medicine id and description based on Medicine Name. Need to add new column Medicine Name in Medication table.

// Add height and weight in SIgnUp page.
// MedicationDetails table ---> Medicationname, Description, image
// In fro0ntend medicationName is dropdown, dynamically get description, add fields for dosage, remove choose file.
// Add new screen for adding patients, 
// PatientName, Relation, Height, Weight(patientId autogenerated, send userId) /patient/add/{userId}
// blood pressure, glucose level, Cholesterol, time information not updating after recent data is entered, working fine when we get data from API.
// need API for up and down arrows

// make text in 4 corners to white or visible


// Change, ahead of choose image from object to filename.
// Edit med, Make form similar to new med, Change edit similar to Four COrners
// Add date search for documents
// endDate > currentDate > StartDate, then prescription count.
// Modify Health Connect, 
// // Calendar

// Modify BP logic so that down and up arrow works.

// redirect to login after signup. -- DONE -- Need to test
// Change datepicker in Medication -- already datepicker is there
// Add a form before installing Fpour Corners, -- DONE -- Need to add condtion for showing the form only if uninstalled


// Medications
// footer for appStore,spacing, background color
// color for background , 4corners
// thin out or remove scroll bar in HealthKnowledgeBase
// background color for healthConnect

// integrate dpocument API's
// reduce height of card in medical conditions screen


// header Opace #5c9a9238

card background transparency #00000024

login rgba(95, 84, 84, 0.38)